import Image from "next/image";
import Head from "next/head";
import Header from "../components/Header";
import HeroImg from "../components/HeroImg";
import SmCard from "../components/SmCard";
import MdCard from "../components/MdCard";
import LgBanner from "../components/LgBanner";

export default function Home({ exploreData, liveAnywhereData, discoverData }) {
  // console.log(liveAnywhere);
  return (
    <div className="">
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      {/* Banner/heroImg */}
      <HeroImg />
      {/* Content*/}
      <main className="px-8 mx-auto mt-16 max-w-7xl sm:px-16 text-primeBlack">
        {/* Explore Nearby Section */}
        <section className="mb-10">
          <h2 className="text-xl font-bold md:text-2xl lg:text-3xl xl:text-4xl">
            Explore nearby
          </h2>
          <div className="grid grid-cols-2 my-4 md:grid-cols-3 lg:grid-cols-4 ">
            {exploreData.map((item, index) => (
              <SmCard
                img={item.img}
                location={item.location}
                distance={item.distance}
                key={index}
              />
            ))}
          </div>
        </section>
        {/* Live anywhere section */}
        <section className="mb-10">
          <h2 className="text-xl font-bold md:text-2xl lg:text-3xl xl:text-4xl">
            Live anywhere
          </h2>
          <div className="flex pl-3 my-4 -ml-3 space-x-3 overflow-scroll scrollbar-hide">
            {liveAnywhereData.map((item, index) => (
              <MdCard img={item.img} title={item.title} key={index} />
            ))}
          </div>
          <LgBanner
            img="https://rebrand.ly/ceviumj"
            title="The Greatest Outdoors"
            alt="bannerImg"
            description="Wishlists curated by Airbnb."
            buttonText="Get Inspired"
          />
        </section>
        {/*Discover Experiences section  */}
        <section className="mb-10">
          <h2 className="text-xl font-bold md:text-2xl lg:text-3xl xl:text-4xl">
            Discover Experiences
          </h2>
          <p className="text-sm md:text-xl lg:text-2xl xl:text-3xl">
            Unique activities with local experts – in person or online.
          </p>
          <div className="flex px-3 my-4 -mx-3 space-x-3 ">
            {discoverData.map((item, index) => (
              <MdCard
                img={item.img}
                title={item.title}
                key={index}
                description={item.description}
                buttonText={item.buttonText}
              />
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
export const getStaticProps = async (ctx) => {
  const resExplore = await fetch("https://rebrand.ly/s3tvrho");
  const exploreData = await resExplore.json();
  if (!exploreData) {
    return {
      notFound: true,
    };
  }
  const resLive = await fetch("https://rebrand.ly/61d709");
  const liveAnywhereData = await resLive.json();
  if (!liveAnywhereData) {
    return {
      notFound: true,
    };
  }
  const resDiscover = await fetch("https://rebrand.ly/9lp0ux1");
  const discoverData = await resDiscover.json();
  if (!discoverData) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      exploreData,
      liveAnywhereData,
      discoverData,
    },
  };
};
